// <auto-generated />
using System;
using HeartLog.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HeartLog.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260520140832_AddSupabaseUserIdToUsers")]
    partial class AddSupabaseUserIdToUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HeartLog.DAL.Models.Emotion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("ParentId", "SortOrder");

                    b.ToTable("Emotions");
                });

            modelBuilder.Entity("HeartLog.DAL.Models.EmotionEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedNever()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "OccurredAt");

                    b.ToTable("EmotionEntries");
                });

            modelBuilder.Entity("HeartLog.DAL.Models.EmotionEntryEmotion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedNever()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmotionEntryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmotionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("EmotionEntryId")
                        .IsUnique()
                        .HasFilter("\"IsPrimary\" = true");

                    b.HasIndex("EmotionEntryId", "EmotionId")
                        .IsUnique();

                    b.HasIndex("EmotionId");

                    b.ToTable("EmotionEntryEmotions");
                });

            modelBuilder.Entity("HeartLog.DAL.Models.EmotionTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmotionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("EmotionId", "Locale")
                        .IsUnique();

                    b.ToTable("EmotionTranslations");
                });

            modelBuilder.Entity("HeartLog.DAL.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("HeartLog.DAL.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedNever()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("SupabaseUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("SupabaseUserId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HeartLog.DAL.Models.Emotion", b =>
                {
                    b.HasOne("HeartLog.DAL.Models.Emotion", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("HeartLog.DAL.Models.EmotionEntry", b =>
                {
                    b.HasOne("HeartLog.DAL.Models.User", "User")
                        .WithMany("EmotionEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HeartLog.DAL.Models.EmotionEntryEmotion", b =>
                {
                    b.HasOne("HeartLog.DAL.Models.Emotion", "Emotion")
                        .WithMany()
                        .HasForeignKey("EmotionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HeartLog.DAL.Models.EmotionEntry", "EmotionEntry")
                        .WithMany("EmotionEntryEmotions")
                        .HasForeignKey("EmotionEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Emotion");

                    b.Navigation("EmotionEntry");
                });

            modelBuilder.Entity("HeartLog.DAL.Models.EmotionTranslation", b =>
                {
                    b.HasOne("HeartLog.DAL.Models.Emotion", "Emotion")
                        .WithMany("Translations")
                        .HasForeignKey("EmotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Emotion");
                });

            modelBuilder.Entity("HeartLog.DAL.Models.Emotion", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("HeartLog.DAL.Models.EmotionEntry", b =>
                {
                    b.Navigation("EmotionEntryEmotions");
                });

            modelBuilder.Entity("HeartLog.DAL.Models.User", b =>
                {
                    b.Navigation("EmotionEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
